### ISSUE TITLE
"Create steps" dropdown is not wide enough

### ISSUE THREAD

**Issue by Andras-Csanyi** [Socolin/resharper-specflow#8]
When the project where to "Create Step" can create the stepdefinition is long then the dropdown not wide enough. See the attached screenshot.

Suggested solution:
- width of drop down aligns to the content it displays

<img width="1090" alt="Screenshot 2021-02-03 at 10 59 48" src="https://user-images.githubusercontent.com/5106373/106730934-32ef0580-660f-11eb-952a-4fe3744a9ee2.png">

**Comment by Socolin** [comment]
The popup seems wide enough but the problem here is that it does not show the filename in case of `partial class`
I'm going to change this, trying to display class more like in autocomplete, the class name on the left, and the namespace on the right. And in case of partial class it's going to open a second popup to choose the file.

**Comment by Socolin** [comment]
Hello,

I've reworked the create step a bit, I need to polish some details (some class should not be listed) but here what it look likes.

![CreateNewStep](https://user-images.githubusercontent.com/539620/107103531-0217f780-67ec-11eb-8f7b-d99d145442ef.gif)

You can grab this build from the Github actions, I'll publish later when I got some bug fixed

**Comment by Socolin** [comment]
The last version has been published on the marketplace if you want to test, you can just update the extension from here

**Comment by Andras-Csanyi** [comment]
> The last version has been published on the marketplace if you want to test, you can just update the extension from here

Awesome! Tomorrow I'm going to take a look at it!
Is the new version compatible the recently published EAP?

**Comment by Socolin** [comment]
> > The last version has been published on the marketplace if you want to test, you can just update the extension from here
> 
> Awesome! Tomorrow I'm going to take a look at it!
> Is the new version compatible the recently published EAP?

Not yet, if it's a trivial update I'll try to build it too this week

**Comment by Andras-Csanyi** [comment]
Looks good! From my side this bug is fixed. Thank you!
